version: '2'
services:
  browser:
    image: bhcr.io/balenablocks/browser-armv7hf # where <arch> is one of aarch64, arm32 or amd64
    privileged: true # required for UDEV to find plugged in peripherals such as a USB mouse
    network_mode: host
    ports:
        - '5011' # management API (optional)
        - '35173' # Chromium debugging port (optional)
  ledmatrix:
    privileged: true
    build: ./ledmatrix
    expose:
      - "80"
